[package]
name = "heros"
version = "0.1.0"
authors = ["lenna_kun"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligned = "0.3.2"
cortex-m-semihosting = "0.3.5"
vcell = "0.1.2"
